[package]
name = "my-little-pal"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.9"
reqwest = { version = "0.12.23", features = ["json"] }
serde = "1.0.219"
tokio = { version = "1.47.1", features = ["full"] }
